config/routes.rb
Caaska::Application.routes.draw do
  resources :devices

  resources :networks do
     get 'ping', :on => :collection
  end

  resources :unit_tools do
     get 'unit', :on => :collection
     get 'tool', :on => :collection
     get 'find', :on => :collection
  end

  resources :tools

  get "home/index"

  resources :credentials

  resources :units do
     get 'check', :on => :collection
     get 'check_unit_tools', :on => :collection
     get 'ping', :on => :collection
  end

  root :to => 'home#index'

end

app/models/tool.rb
class Tool < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :unit_tools
  validates :name, :presence => true, :uniqueness =>true

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  # GET /tools
  # GET /tools.json
  def index
    @tools = Tool.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tools }
    end
  end

  # GET /tools/1
  # GET /tools/1.json
  def show
    @tool = Tool.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tool }
    end
  end

  # GET /tools/new
  # GET /tools/new.json
  def new
    @tool = Tool.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tool }
    end
  end

  # GET /tools/1/edit
  def edit
    @tool = Tool.find(params[:id])
  end

  # POST /tools
  # POST /tools.json
  def create
    @tool = Tool.new(params[:tool])

    respond_to do |format|
      if @tool.save
        format.html { redirect_to @tool, notice: 'Tool was successfully created.' }
        format.json { render json: @tool, status: :created, location: @tool }
      else
        format.html { render action: "new" }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tools/1
  # PUT /tools/1.json
  def update
    @tool = Tool.find(params[:id])

    respond_to do |format|
      if @tool.update_attributes(params[:tool])
        format.html { redirect_to @tool, notice: 'Tool was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tools/1
  # DELETE /tools/1.json
  def destroy
    @tool = Tool.find(params[:id])
    @tool.destroy

    respond_to do |format|
      format.html { redirect_to tools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/_form.html.erb
<%= form_for(@tool) do |f| %>
  <% if @tool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tool.errors.count, "error") %> prohibited this tool from being saved:</h2>

      <ul>
      <% @tool.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tools/edit.html.erb
<h1>Editing tool</h1>

<%= render 'form' %>

<%= link_to 'Show', @tool %> |
<%= link_to 'Back', tools_path %>

app/views/tools/index.html.erb
<h1>Listing tools</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tools.each do |tool| %>
  <tr>
    <td><%= tool.name %></td>
    <td><%= tool.description %></td>
    <td><%= link_to 'Show', tool %></td>
    <td><%= link_to 'Show where available', :controller => :unit_tools, :action => :find, :tool =>tool %></td>
    <td><%= link_to 'Edit', edit_tool_path(tool) %></td>
    <td><%= link_to 'Destroy', tool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tool', new_tool_path %>

app/views/tools/new.html.erb
<h1>New tool</h1>

<%= render 'form' %>

<%= link_to 'Back', tools_path %>

app/views/tools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tool.name %>
</p>

<p>
  <b>Description:</b>
  <%= @tool.description %>
</p>

<%= link_to 'New Tool', new_tool_path %> |
<%= link_to 'Edit', edit_tool_path(@tool) %> |
<%= link_to 'Back', tools_path %>