config/routes.rb
Caaska::Application.routes.draw do
  resources :devices

  resources :networks do
     get 'ping', :on => :collection
  end

  resources :unit_tools do
     get 'unit', :on => :collection
     get 'tool', :on => :collection
     get 'find', :on => :collection
  end

  resources :tools

  get "home/index"

  resources :credentials

  resources :units do
     get 'check', :on => :collection
     get 'check_unit_tools', :on => :collection
     get 'ping', :on => :collection
  end

  root :to => 'home#index'

end

app/models/network.rb
require 'resolv'

class Network < ActiveRecord::Base
  attr_accessible :end_ip, :start_ip  
  validates :end_ip, :presence => true,
            :uniqueness => true, :format => { :with => Resolv::IPv4::Regex } 
  validates :start_ip, :presence => true, 
            :uniqueness => true, :format => { :with => Resolv::IPv4::Regex }

  def self.validate_ip(ip)
      if(Resolv::IPv4::Regex.match(ip))
          [$1.to_i, $2.to_i, $3.to_i, $4.to_i]
      end
  end

  def self.ip2num(ip)
      if(i = self.validate_ip(ip))
          i[0]*2**24 + i[1]*2**16 +i[2]*2**8 + i[3]
      end
  end

  def self.num2ip(num)
      a = num / 2**24 
      num = num % 2**24
      b = num / 2**16
      num = num % 2**16
      c = num / 2**8
      d = num % 2**8
      "#{a}.#{b}.#{c}.#{d}"
  end

  def ips
     s = Network.ip2num(self.start_ip)
     e = Network.ip2num(self.end_ip)

     ips = Array.new
     for ip in s..e 
        ips.push(Network.num2ip(ip))
     end
     ips
  end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  # GET /networks
  # GET /networks.json
  def index
    @networks = Network.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @networks }
    end
  end

  # GET /networks/1
  # GET /networks/1.json
  def show
    @network = Network.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @network }
    end
  end

  # GET /networks/new
  # GET /networks/new.json
  def new
    @network = Network.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @network }
    end
  end

  # GET /networks/1/edit
  def edit
    @network = Network.find(params[:id])
  end

  # POST /networks
  # POST /networks.json
  def create
    @network = Network.new(params[:network])

    respond_to do |format|
      if @network.save
        format.html { redirect_to @network, notice: 'Network was successfully created.' }
        format.json { render json: @network, status: :created, location: @network }
      else
        format.html { render action: "new" }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /networks/1
  # PUT /networks/1.json
  def update
    @network = Network.find(params[:id])

    respond_to do |format|
      if @network.update_attributes(params[:network])
        format.html { redirect_to @network, notice: 'Network was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /networks/1
  # DELETE /networks/1.json
  def destroy
    @network = Network.find(params[:id])
    @network.destroy

    respond_to do |format|
      format.html { redirect_to networks_url }
      format.json { head :no_content }
    end
  end

  def ping 
    @network = Network.find(params[:id])
    devices  = Scanner.ping_each(@network.ips)
    devices.each do |device|
       d = Device.find_by_ip(device)
       d = Device.new if d.nil?
       d.ip = device
       d.network = @network
       d.ping = true
       d.save!
    end
    list = devices.join(',')
    
    respond_to do |format|
       format.html { redirect_to @network, notice: "Found #{list}." }
    end
  end
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/views/networks/_form.html.erb
<%= form_for(@network) do |f| %>
  <% if @network.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@network.errors.count, "error") %> prohibited this network from being saved:</h2>

      <ul>
      <% @network.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_ip %><br />
    <%= f.text_field :start_ip %>
  </div>
  <div class="field">
    <%= f.label :end_ip %><br />
    <%= f.text_field :end_ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/networks/edit.html.erb
<h1>Editing network</h1>

<%= render 'form' %>

<%= link_to 'Show', @network %> |
<%= link_to 'Back', networks_path %>

app/views/networks/index.html.erb
<h1>Listing networks</h1>

<table>
  <tr>
    <th>Start ip</th>
    <th>End ip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @networks.each do |network| %>
  <tr>
    <td><%= network.start_ip %></td>
    <td><%= network.end_ip %></td>
    <td><%= link_to 'Show', network %></td>
    <td><%= link_to 'Edit', edit_network_path(network) %></td>
    <td><%= link_to 'Ping', :action => :ping, :id => network %></td>
    <td><%= link_to 'Destroy', network, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Network', new_network_path %>

app/views/networks/new.html.erb
<h1>New network</h1>

<%= render 'form' %>

<%= link_to 'Back', networks_path %>

app/views/networks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start ip:</b>
  <%= @network.start_ip %>
</p>

<p>
  <b>End ip:</b>
  <%= @network.end_ip %>
</p>


<%= link_to 'Edit', edit_network_path(@network) %> |
<%= link_to 'Back', networks_path %>