config/routes.rb
Caaska::Application.routes.draw do
  resources :devices

  resources :networks do
     get 'ping', :on => :collection
  end

  resources :unit_tools do
     get 'unit', :on => :collection
     get 'tool', :on => :collection
     get 'find', :on => :collection
  end

  resources :tools

  get "home/index"

  resources :credentials

  resources :units do
     get 'check', :on => :collection
     get 'check_unit_tools', :on => :collection
     get 'ping', :on => :collection
  end

  root :to => 'home#index'

end

app/models/credential.rb
class Credential < ActiveRecord::Base
  attr_accessible :count, :password, :username
end

app/controllers/credentials_controller.rb
class CredentialsController < ApplicationController
  # GET /credentials
  # GET /credentials.json
  def index
    @credentials = Credential.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @credentials }
    end
  end

  # GET /credentials/1
  # GET /credentials/1.json
  def show
    @credential = Credential.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @credential }
    end
  end

  # GET /credentials/new
  # GET /credentials/new.json
  def new
    @credential = Credential.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @credential }
    end
  end

  # GET /credentials/1/edit
  def edit
    @credential = Credential.find(params[:id])
  end

  # POST /credentials
  # POST /credentials.json
  def create
    @credential = Credential.new(params[:credential])

    respond_to do |format|
      if @credential.save
        format.html { redirect_to @credential, notice: 'Credential was successfully created.' }
        format.json { render json: @credential, status: :created, location: @credential }
      else
        format.html { render action: "new" }
        format.json { render json: @credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /credentials/1
  # PUT /credentials/1.json
  def update
    @credential = Credential.find(params[:id])

    respond_to do |format|
      if @credential.update_attributes(params[:credential])
        format.html { redirect_to @credential, notice: 'Credential was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credentials/1
  # DELETE /credentials/1.json
  def destroy
    @credential = Credential.find(params[:id])
    @credential.destroy

    respond_to do |format|
      format.html { redirect_to credentials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/credentials_helper.rb
module CredentialsHelper
end

app/views/credentials/_form.html.erb
<%= form_for(@credential) do |f| %>
  <% if @credential.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credential.errors.count, "error") %> prohibited this credential from being saved:</h2>

      <ul>
      <% @credential.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credentials/edit.html.erb
<h1>Editing credential</h1>

<%= render 'form' %>

<%= link_to 'Show', @credential %> |
<%= link_to 'Back', credentials_path %>

app/views/credentials/index.html.erb
<h1>Listing credentials</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th>Count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @credentials.each do |credential| %>
  <tr>
    <td><%= credential.username %></td>
    <td><%= credential.password %></td>
    <td><%= credential.count %></td>
    <td><%= link_to 'Show', credential %></td>
    <td><%= link_to 'Edit', edit_credential_path(credential) %></td>
    <td><%= link_to 'Destroy', credential, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Credential', new_credential_path %>

app/views/credentials/new.html.erb
<h1>New credential</h1>

<%= render 'form' %>

<%= link_to 'Back', credentials_path %>

app/views/credentials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @credential.username %>
</p>

<p>
  <b>Password:</b>
  <%= @credential.password %>
</p>

<p>
  <b>Count:</b>
  <%= @credential.count %>
</p>


<%= link_to 'Edit', edit_credential_path(@credential) %> |
<%= link_to 'Back', credentials_path %>