config/routes.rb
Caaska::Application.routes.draw do
  resources :devices

  resources :networks do
     get 'ping', :on => :collection
  end

  resources :unit_tools do
     get 'unit', :on => :collection
     get 'tool', :on => :collection
     get 'find', :on => :collection
  end

  resources :tools

  get "home/index"

  resources :credentials

  resources :units do
     get 'check', :on => :collection
     get 'check_unit_tools', :on => :collection
     get 'ping', :on => :collection
  end

  root :to => 'home#index'

end

app/models/unit.rb
require 'resolv'

class Unit < ActiveRecord::Base
  attr_accessible :description, :ip, :password, :username
  has_many :unit_tools, :dependent => :destroy
  validates :ip, :presence => true,
            :uniqueness => true, :format => { :with => Resolv::IPv4::Regex }

  def check_tool(tool)
    if(!tool.nil? and !tool.name.blank?)
      begin
         require 'net/ssh'
         result = 'nothing'
         Net::SSH.start( self.ip, self.username, :password => self.password) do|ssh|
           result = ssh.exec!("which #{tool.name}")
         end
         t = UnitTool.new
         t.unit = self
         t.tool = tool
         t.path = result
         t.save!
         result +' Fine!'
      rescue Exception => e 
	 e.message
      end
    end
  end

  def check_tools
     tools = Tool.find(:all)
     tools.each do |t|
       status = self.check_tool(t)
       self.description = self.description + "\n" + status;
     end
     self.save!
  end

  def check_credential
   if (!self.ip.blank?)                                                                                
     begin
       require 'net/ssh'
       Net::SSH.start( self.ip, self.username, :password => self.password) do|ssh|
         ssh.exec('ls')
       end
       'Successfully authenticated'
     rescue Net::SSH::AuthenticationFailed => e
       "Invalid Credentials: #{e}"
     rescue SocketError => e
       "Invalid Host: #{e}"
     rescue Exception => e  
        e.message  
     end
   else
     "Ip is blank"
   end
  end

  def update_description(desc)
     self.description = desc
     self.save!
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  # GET /units
  # GET /units.json
  def index
    @units = Unit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @units }
    end
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @unit = Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/new
  # GET /units/new.json
  def new
    @unit = Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render json: @unit, status: :created, location: @unit }
      else
        format.html { render action: "new" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.json
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end

  def check_unit_tools
    @unit = Unit.find(params[:unit])
    result = @unit.check_tools

    respond_to do |format|
       format.html{redirect_to @unit, notice: result }
    end
  end

  def check
    @unit = Unit.find(params[:unit])
    result = @unit.check_credential
    @unit.update_description(result)

    respond_to do |format|
       format.html{redirect_to @unit, notice: result }
    end
  end

  def ping 
    @unit = Unit.find(params[:unit])
    #result = @unit.ping
    result = Scanner.ping(@unit.ip)
    @unit.update_description("Ping result #{result}")

    respond_to do |format|
       format.html{redirect_to @unit, notice: result }
    end
  end
end

app/helpers/unit_helper.rb
module UnitHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/check.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @unit.id %>
</p>

<p>
  <b>Ip:</b>
  <%= @unit.ip %>
</p>

<p>
  <b>Description:</b>
  <%= @unit.description %>
</p>

<p>
  <b>Username:</b>
  <%= @unit.username %>
</p>

<p>
  <b>Password:</b>
  <%= @unit.password %>
</p>


<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Listing units</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Ip</th>
    <th>Description</th>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @units.each do |unit| %>
  <tr>
    <td><%= unit.id %></td>
    <td><%= unit.ip %></td>
    <td><%= unit.description %></td>
    <td><%= unit.username %></td>
    <td><%= unit.password %></td>
    <td><%= link_to 'Show', unit %></td>
    <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
    <td><%= link_to 'Ping', :action => :ping, :unit => unit %></td>
    <td><%= link_to 'Check', :action => :check, :unit => unit %></td> 
    <td><%= link_to 'Check Unit Tools', :action => :check_unit_tools, :unit => unit %></td>
    <td><%= link_to 'Show Unit Tools', :controller => :unit_tools, :action => :find, :unit => unit %></td>
    <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @unit.id %>
</p>

<p>
  <b>Ip:</b>
  <%= @unit.ip %>
</p>

<p>
  <b>Description:</b>
  <%= @unit.description %>
</p>

<p>
  <b>Username:</b>
  <%= @unit.username %>
</p>

<p>
  <b>Password:</b>
  <%= @unit.password %>
</p>

<%= link_to 'New Unit', new_unit_path %> |
<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>